parameters:
  filePathOnDatabricks: '/$(Build.Repository.Name)/$(Build.SourceBranch)'
steps:
- task: PowerShell@2
  displayName: 'Upload Scripts to [DatabricksDestination = southcentralus]'
  inputs:
    arguments: '-ClientId "$(DataHarborServicePrincipalId)" -ClientSecret "$(DataHarborServicePrincipalKey)" -Tenant "72f988bf-86f1-41af-91ab-2d7cd011db47" -SubscriptionId "2aef373f-4686-40a4-b75d-8221b6e666ab" -ResourceGroupName "cdedatabrickssouthcentralRG" -WorkspaceName "CDEDatabricksSouthCentral" -PathOnBuildingAgent "$(Build.SourcesDirectory)\src\MyProject\Databricks" -Environment southcentralus -DatabricksWorkspacePath "${{ parameters.filePathOnDatabricks }}"'
    filePath: $(Build.SourcesDirectory)/.pipelines/buildScripts/UploadFilesToDatabricks.ps1
    targetType: filePath
